### PR TITLE
Homepage Carousel

### PR DESCRIPTION
**Pull request by gonzalez-mark**

### CODE REVIEW

**Review by KhanWhale — CHANGES_REQUESTED** [review]
1. Can you make sure that the bear for April 16th is now a valid link (on the registration page). You can see how the other ones have been made into links to make sure that works. Also deactivate the old typeforms. This isn't your fault, just something that needs to be incorporated into the repo
2. Also, this is just a stylistic suggestion from me, feel free to ignore it, but I feel like it would be nice to have the carousel arrows stand out a little more? Not a big thing though

**Review by gonzalez-mark — COMMENTED** [review]
I fixed the link. I think the arrows' yellow color stands out well from the thumbnails: facilities navigation.

**Review by gonzalez-mark — COMMENTED** [review]
Good

**Review by KhanWhale — APPROVED** [review]
Looks good! Thanks for fixing the links.

**Pull request merged**
